# generated by Git for Windows
echo "Don't Assume It - Prove it"
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# Some fancy functions
man(){ $1 --help; }
export PATH="$PATH:$HOME/scripts"
